version: '2'
services:
  nginx-proxy:
    image: billsb/alpine-nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: billsb/alpine-python-whoami
    environment:
      - VIRTUAL_HOST=whoami.local
